
name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run preprocessing
        run: |
          source venv/bin/activate
          python preprocess.py

      - name: Train model
        run: |
          source venv/bin/activate
          python train.py

      - name: Build Docker image
        run: |
          docker build -t mlops-heart-disease .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 mlops-heart-disease

      - name: Test the model
        run: |
          sleep 10  # Wait for the server to start
          curl -X POST -H "Content-Type: application/json" -d '[{"age": 63, "sex": 1, "cp": 3, "trestbps": 145, "chol": 233, "fbs": 1, "restecg": 0, "thalach": 150, "exang": 0, "oldpeak": 2.3, "slope": 3, "ca": 0, "thal": 6}]' http://localhost:5000/predict
