name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv mlops-env
        source mlops-env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Run preprocess script
      run: |
        source mlops-env/bin/activate
        python preprocess.py
    - name: Run training script
      run: |
        source mlops-env/bin/activate
        python train.py
    - name: Start Flask app
      run: |
        source mlops-env/bin/activate
        nohup python app.py > server.log 2>&1 &
      shell: bash

    - name: Wait for the server to start
      run: sleep 20

    - name: Test Flask app
      run: |
        source mlops-env/bin/activate
        curl -X POST -H "Content-Type: application/json" \
             -d '[{"age": 63, "sex": 1, "cp": 3, "trestbps": 145, "chol": 233, "fbs": 1, "restecg": 0, "thalach": 150, "exang": 0, "oldpeak": 2.3, "slope": 3, "ca": 0, "thal": 6}]' \
             http://localhost:5000/predict
      shell: bash

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mlops-heart-disease:latest
